select DISTINCT
DELETED_VAPP.VAPP_ID,
DELETED_VAPP.VAPP_NAME,
DELETED_VAPP.CPU,
DELETED_VAPP.MEMORY_SIZE_MB,
DELETED_VAPP.TOTAL_HDDGB,
DELETED_VAPP.LAST_MAX_COST,
DELETED_VAPP.AUTHER1,
DELETED_VAPP.AUTHER2,
DELETED_VAPP.DELETE_DATE


from DELETED_VAPP ,VCD_USER
where
(VCD_USER.VAPP_ID = DELETED_VAPP.VAPP_ID   and  VCD_USER.USER_ID = /* userID */99)
OR
DELETED_VAPP.AUTHER1 = /* userID */99
OR
DELETED_VAPP.AUTHER2 = /* userID */99

order by DELETED_VAPP.DELETE_DATE asc
;


